### ISSUE TITLE
new Update crashing homebridge

### ISSUE THREAD

**Issue by Hopflnger** [vvpossible/homebridge_yeelight#64] opened 2018-09-20 07:28 UTC
Load homebridge-yeelight.yeelight
[2018-9-20 07:27:21] [homebridge-yeelight.yeelight] YeePlatform Init

/usr/local/lib/node_modules/homebridge-yeelight/index.js:20
    this.noble          = config.noble === undefined ? true : config.noble;
                                 ^
TypeError: Cannot read property 'noble' of null
    at new YeePlatform (/usr/local/lib/node_modules/homebridge-yeelight/index.js:20:34)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:346:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
pi@raspberrypi:~ $

**Comment by vvpossible** [comment] 2018-09-20 08:16
en....  I didn't see this issue on my test bed, looks like some pull request brings in some regression problem. I will fix it.

**Comment by vvpossible** [comment] 2018-09-20 08:37
please try update the plugin again and see whether the issue is fixed

**Comment by Hopflnger** [comment] 2018-09-20 08:46
Just reinstalled. Plugin is starting now, but fails some steps later.

[2018-9-20 08:44:54] [homebridge-yeelight.yeelight] DidFinishLaunching
[2018-9-20 08:44:54] [homebridge-yeelight.yeelight] no ble cap, skip ble device discovery
Error: listen EADDRINUSE :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:127:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:96:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
pi@raspberrypi:~ $

**Comment by Hopflnger** [comment] 2018-09-20 10:27
You are right. There was a second instance running. After reboot it runs all fine until now!

**Comment by vvpossible** [comment] 2018-09-20 10:28
good news. close this issue.

**Closed by vvpossible** 2018-09-20 10:28 UTC
